import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { AppNavbar } from "@/components/ui/app-navbar";
import { VapiWidgetComponent } from "@/components/vapi-widget";
import { SocialShareProvider } from "@/components/social/social-share-provider";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="white"
            enableSystem
            disableTransitionOnChange
          >
            <SocialShareProvider>
              <div className="min-h-screen">
                <AppNavbar />
                <main>{children}</main>

                {/* Vapi Widget - will only render if environment variables are set */}
                <VapiWidgetComponent
                  publicKey={process.env.NEXT_PUBLIC_VAPI_API_KEY || ""}
                  assistantId={process.env.NEXT_PUBLIC_VAPI_ASSISTANT_ID || ""}
                  mode="chat"
                  theme="light"
                  position="bottom-right"
                  size="full"
                  accentColor="#14B8A6"
                  buttonBaseColor="#000000"
                  buttonAccentColor="#FFFFFF"
                  mainLabel="Talk with Sarthi"
                  emptyChatMessage="Namaste! I'm Sarthi, your spiritual journey companion. How can I help you explore Ujjain today?"
                  emptyVoiceMessage="Click to start a voice conversation with your spiritual guide"
                />
              </div>
            </SocialShareProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
